name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: self-hosted
    env:
      TF_VAR_db_username: ${{ secrets.TF_VAR_db_USERNAME }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_db_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        shell: powershell
        working-directory: ${{ github.workspace }}/env/dev
        run: terraform init -reconfigure -input=false

      - name: Terraform Plan
        shell: powershell
        working-directory: ${{ github.workspace }}/env/dev
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform Show Plan
        shell: powershell
        working-directory: ${{ github.workspace }}/env/dev
        run: terraform show -no-color tfplan

      - name: Terraform Apply
        shell: powershell
        working-directory: ${{ github.workspace }}/env/dev
        run: terraform apply -input=false -auto-approve tfplan

      - name: Terraform State List After Apply
        shell: powershell
        working-directory: ${{ github.workspace }}/env/dev
        run: terraform state list

      - name: Terraform Outputs After Apply
        shell: powershell
        working-directory: ${{ github.workspace }}/env/dev
        run: terraform output