name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: self-hosted

    env:
      TF_VAR_db_username: ${{ secrets.TF_VAR_db_username }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        shell: powershell
        run: terraform -chdir=env/dev init -reconfigure -input=false

      - name: Terraform Plan
        shell: powershell
        run: terraform -chdir=env/dev plan -input=false -no-color -out=tfplan

      - name: Terraform Show Plan
        shell: powershell
        run: terraform -chdir=env/dev show -no-color tfplan

      - name: Terraform Apply
        shell: powershell
        run: terraform -chdir=env/dev apply -input=false -auto-approve tfplan

      - name: Terraform State List After Apply
        shell: powershell
        run: terraform -chdir=env/dev state list

      - name: Terraform Output After Apply
        shell: powershell
        run: terraform -chdir=env/dev output